version: '3.8'
services:
  web:
    restart: always
    command: python manage.py run -h 0.0.0.0 -p 80
    build: .
    ports:
      - "80:80"
    volumes:
      - ./enrollment/application/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresDB
  db:
    restart: always
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgresDB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  postgres_data:
    external: false